apiVersion: v1
kind: Namespace
metadata:
  name: system-two
  annotations:
    argocd.argoproj.io/sync-wave: "-2" # Ensure the namespace is created before the argo project

---

apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: system-two
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1" # Ensure argo project is created before any apps
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: This is an example system, consisting of multiple independently deployable apps
  sourceRepos:
    - '*'

  destinations:
    - namespace: system-two
      server: https://kubernetes.default.svc

---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: system-two
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1" # Ensure argo project is created before any apps
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: This is another example system, consisting of multiple independently deployable apps
  sourceRepos:
    - '*'

  destinations:
    - namespace: system-two
      server: https://kubernetes.default.svc

  
