apiVersion: v1
kind: Namespace
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
  name: manhattan
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: manhattan
  namespace: argocd
spec:
  description: description
  destinations:
  - namespace: manhattan-centrifuge
    server: https://kubernetes.default.svc
  sourceRepos:
  - https://github.com/bernos/argocd-demo-web-service
