apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: system-one
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1" # Ensure argo project is created before any apps
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: This is an example system, consisting of multiple independently deployable apps
  sourceRepos:
    - '*'

  destinations:
    - namespace: system-one
      server: https://kubernetes.default.svc

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: system-one
  namespace: system-one
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: system-one
    server: https://kubernetes.default.svc
  source:
    path: production/system-one
    repoURL: https://github.com/bernos/argocd-demo-environments.git
    targetRevision: HEAD
    directory:
      recurse: true
  project: system-one
  
